import { endent, map } from '@dword-design/functions'

import { BADGES_CLASS } from './model/constants'
import getRepositoryBadges from './model/get-repository-badges'

const run = async () => {
  let style = document.querySelector('style.github-repository-list-badges')
  if (style) {
    style.remove()
  }
  style = document.createElement('style')
  style.classList.add('github-repository-list-badges')
  style.type = 'text/css'
  style.appendChild(
    document.createTextNode(endent`
    @keyframes ldio-12yqow1lcnh {
      0% { transform: translate(-50%,-50%) rotate(0deg); }
      100% { transform: translate(-50%,-50%) rotate(360deg); }
    }
    .ldio-12yqow1lcnh div {
      position: absolute;
      width: 60px;
      height: 60px;
      border: 10px solid #dddddd;
      border-top-color: transparent;
      border-radius: 50%;
    }
    .ldio-12yqow1lcnh div {
      animation: ldio-12yqow1lcnh 1s linear infinite;
      top: 50px;
      left: 50px
    }
    .loadingio-spinner-rolling-ah2188o9kws {
      width: 40px;
      height: 40px;
      display: inline-block;
      overflow: hidden;
      background: none;
    }
    .ldio-12yqow1lcnh {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(0.4);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-12yqow1lcnh div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
  `)
  )
  document.getElementsByTagName('head')[0].appendChild(style)

  const $headlines = document.querySelectorAll('#user-repositories-list h3')
  for (const $headline of $headlines) {
    const $headlineContainer = $headline.parentNode

    const $repository = $headlineContainer.parentNode
    let $badges = $repository.querySelector(`.${BADGES_CLASS}`)
    if ($badges) {
      $badges.remove()
    }
    $badges = document.createElement('div')
    $badges.classList.add(BADGES_CLASS)
    $badges.innerHTML = endent`
      <div class="loadingio-spinner-rolling-ah2188o9kws"><div class="ldio-12yqow1lcnh">
      <div></div>
      </div></div>
    `
    $headlineContainer.after($badges)
  }

  const $badges = await ($headlines
    |> map($headline => $headline.querySelector('a').textContent.trim())
    |> map(getRepositoryBadges)
    |> Promise.all)
  for (let index = 0; index < $badges.length; index += 1) {
    const $repoBadges = $badges[index]

    const $badgesContainer = $headlines[
      index
    ].parentNode.parentNode.querySelector(`.${BADGES_CLASS}`)
    if ($repoBadges) {
      $badgesContainer.replaceWith($repoBadges)
    } else {
      $badgesContainer.remove()
    }
  }
}
run()
