import endent from 'endent';
import pWaitFor from 'p-wait-for';

export default defineContentScript({
  main: async () => {
    let style = document.querySelector<HTMLStyleElement>(
      'style.github-repository-list-badges',
    );

    if (style) {
      style.remove();
    }

    style = document.createElement('style');
    style.classList.add('github-repository-list-badges');
    style.type = 'text/css';

    style.append(
      document.createTextNode(endent`
        @keyframes ldio-12yqow1lcnh {
          0% { transform: translate(-50%,-50%) rotate(0deg); }
          100% { transform: translate(-50%,-50%) rotate(360deg); }
        }
        .ldio-12yqow1lcnh div {
          position: absolute;
          width: 60px;
          height: 60px;
          border: 10px solid #dddddd;
          border-top-color: transparent;
          border-radius: 50%;
        }
        .ldio-12yqow1lcnh div {
          animation: ldio-12yqow1lcnh 1s linear infinite;
          top: 50px;
          left: 50px
        }
        .loadingio-spinner-rolling-ah2188o9kws {
          width: 40px;
          height: 40px;
          display: inline-block;
          overflow: hidden;
          background: none;
        }
        .ldio-12yqow1lcnh {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(0.4);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-12yqow1lcnh div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
      `),
    );

    document.querySelectorAll('head')[0].append(style);

    // Wait until all headlines have their <a> tags loaded
    await pWaitFor(
      () => {
        const $headlines = document.querySelectorAll(
          '#user-repositories-list h3',
        );

        return [...$headlines].every(
          $headline => $headline.querySelector('a') !== null,
        );
      },
      { interval: 100 },
    );

    const $headlines = document.querySelectorAll('#user-repositories-list h3');

    for (const $headline of $headlines) {
      const $headlineContainer = $headline.parentNode as HTMLElement;
      const $repository = $headlineContainer.parentNode!;
      let $badges = $repository.querySelector(`.${BADGES_CLASS}`);

      if ($badges) {
        $badges.remove();
      }

      $badges = document.createElement('div');
      $badges.classList.add(BADGES_CLASS);

      $badges.innerHTML = endent`
        <div class="loadingio-spinner-rolling-ah2188o9kws"><div class="ldio-12yqow1lcnh">
        <div></div>
        </div></div>
      `;

      $headlineContainer.after($badges);
    }

    const $badges = await Promise.all(
      [...$headlines]
        .map($headline => $headline.querySelector('a')!.textContent.trim())
        .map(repoName => getRepositoryBadges(repoName)),
    );

    for (const [index, $repoBadges] of $badges.entries()) {
      const $badgesContainer = $headlines[
        index
      ]!.parentNode!.parentNode!.querySelector(`.${BADGES_CLASS}`)!;

      if ($repoBadges) {
        $badgesContainer.replaceWith($repoBadges);
      } else {
        $badgesContainer.remove();
      }
    }
  },
  matches: ['https://github.com/*?*tab=repositories*'],
});
